yarnPath: .yarn/releases/yarn-4.6.0.cjs

nodeLinker: node-modules


supportedArchitectures: 
  os:
    - 'darwin'
    - 'linux'
    - 'win32'
  cpu:
    - 'x64'
    - 'x86'
    - 'arm'
    - 'arm64'
    - 'ia32'
  libc:
    - 'glibc'
    - 'musl'